apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      run: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic-test
        image: dcanadillas/spring-petclinic:latest
        command:
        ports:
          - containerPort: 9090
            protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: petclinic-service
spec:
  type: LoadBalancer
  selector:
    app: petclinic
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: staging
 name: test-jenkins
rules:
- apiGroups: [""]
  resources: ["services","deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: test-jenkins-binding
 namespace: staging
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: cbcore
roleRef:
 kind: Role
 name: test-jenkins
 apiGroup: rbac.authorization.k8s.io